### ISSUE TITLE
Feature request: Allow permanent display of on-hover information

### ISSUE THREAD

**Issue by brandon-fryslie** [scottmwyant/vscode-gcode#1]
I'm very new to g-code, and the on-hover information is fantastic and indispensable.  It would be even better if we could always display the information on the same line after the line ends.  I'm not sure if you've used IntelliJ, but that IDE presents information in that way often.  I think it would make this plugin even better.

Thanks so much for the excellent plugin!

**Comment by scottmwyant** [comment]
Excellent idea!

I'm enjoying a little break from this project now that I finally got it on marketplace, but I'll put this "on the roadmap".

Note to self: https://vscode.rocks/decorations/

**Comment by scottmwyant** [comment]
# Proof of Concept

@brandon-fryslie I looked at implementing your idea of "annotation after the end of the line" (called "decoration" in VS Code) but I didn't like how it was shaping up.  What happens when there are multiple words on the same line, what if the definition is really verbose, and how to handle multiple instances of a word? 

Today I had the idea to simply display the dictionary.  This would work like the native command "Markdown: Open Preview to the Side".  See screenshot below.  I think this looks promising.

![image](https://user-images.githubusercontent.com/29161635/116768430-7685bf80-aa04-11eb-9bf7-dc0b1d8749fe.png)

**Comment by scottmwyant** [comment]
# Feature released in v0.2.0 

Added the `G-Code: Show the dictionary` command in [v0.2.0](https://github.com/scottmwyant/vscode-gcode/releases/tag/v0.2.0), which is now live on the marketplace. 

<p align="center"><img src="https://user-images.githubusercontent.com/29161635/117580501-35f20a00-b0c6-11eb-818e-7715809e2326.gif" alt="icon" height="400px" width="800px"></p>
